# Generated by Django 5.2.16 on 2026-10-01 07:26

import audit.security
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0010_syncrun_provider_version_provenance'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('form_type', models.CharField(max_length=5)),
                ('accepted_at', models.DateTimeField()),
                ('period_of_report', models.DateField(blank=True, null=True)),
                ('primary_document', models.CharField(max_length=255)),
                ('filing_url', models.URLField(max_length=500, validators=[audit.security.validate_safe_base_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='companies.company')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.sourceevidence')),
            ],
        ),
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, validators=[audit.security.validate_safe_base_url])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='filings.filing')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.sourceevidence')),
            ],
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['company', '-accepted_at'], name='filings_fil_company_d1d6c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.CheckConstraint(condition=models.Q(('accession_number__regex', '^[0-9]{10}-[0-9]{2}-[0-9]{6}$')), name='filings_accession_format'),
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.CheckConstraint(condition=models.Q(('form_type__in', ('8-K', '10-Q', '10-K', '6-K', '20-F', '40-F'))), name='filings_form_target'),
        ),
        migrations.AddConstraint(
            model_name='filingdocument',
            constraint=models.UniqueConstraint(fields=('filing', 'filename'), name='filings_doc_filename_unique'),
        ),
        migrations.AddConstraint(
            model_name='filingdocument',
            constraint=models.CheckConstraint(condition=models.Q(('filename', ''), _negated=True), name='filings_doc_filename_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='filingdocument',
            constraint=models.CheckConstraint(condition=models.Q(('document_type', ''), _negated=True), name='filings_doc_type_nonempty'),
        ),
    ]
