# Generated by Django 5.2.16 on 2026-10-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_remove_auditrecord_audit_record_target_type_valid_and_more'),
        ('companies', '0001_initial'),
        ('filings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='reported_items',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.CheckConstraint(condition=models.Q(('reported_items', ''), ('reported_items__regex', '^[0-9]{1,2}\\.[0-9]{2}(,[0-9]{1,2}\\.[0-9]{2})*$'), _connector='OR'), name='filings_reported_items_canonical'),
        ),
    ]
