# Generated by Django 5.2.16 on 2026-07-13 04:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('sec', 'SEC'), ('ir', 'Investor relations'), ('earnings_calendar', 'Earnings calendar'), ('index', 'Index'), ('manual', 'Manual')], max_length=32)),
                ('base_url', models.URLField(blank=True)),
                ('is_official', models.BooleanField(default=False)),
                ('provider_adapter', models.CharField(blank=True, max_length=255)),
                ('license_notes', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'constraints': [models.CheckConstraint(condition=models.Q(('source_type__in', ('sec', 'ir', 'earnings_calendar', 'index', 'manual'))), name='audit_data_source_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_count', models.PositiveBigIntegerField(default=0)),
                ('created_count', models.PositiveBigIntegerField(default=0)),
                ('updated_count', models.PositiveBigIntegerField(default=0)),
                ('skipped_count', models.PositiveBigIntegerField(default=0)),
                ('failed_count', models.PositiveBigIntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, max_length=2000)),
                ('code_version', models.CharField(blank=True, max_length=100)),
                ('parser_version', models.CharField(blank=True, max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='audit.datasource')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['job_type', 'status', 'started_at'], name='audit_syncr_job_typ_27bb85_idx'), models.Index(fields=['source', 'status', 'started_at'], name='audit_syncr_source__363808_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'job_type', 'idempotency_key'), name='audit_sync_run_window_key_unique'), models.CheckConstraint(condition=models.Q(('fetched_count__gte', 0), ('created_count__gte', 0), ('updated_count__gte', 0), ('skipped_count__gte', 0), ('failed_count__gte', 0)), name='audit_sync_run_counts_non_negative'), models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='audit_sync_run_finish_after_start'), models.CheckConstraint(condition=models.Q(('heartbeat_at__gte', models.F('started_at'))), name='audit_sync_run_heartbeat_after_start'), models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('heartbeat_at__lte', models.F('finished_at')), _connector='OR'), name='audit_sync_run_heartbeat_before_finish'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'running'), ('finished_at__isnull', True)), models.Q(('status__in', ('succeeded', 'partial', 'failed', 'skipped')), ('finished_at__isnull', False)), _connector='OR'), name='audit_sync_run_status_finish_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('job_type', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='audit_sync_run_keys_not_empty')],
            },
        ),
    ]
