# Generated by Django 5.2.16 on 2026-07-13 05:41

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2048)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('encoding', models.CharField(blank=True, max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.BinaryField(max_length=1048576)),
                ('payload_size_bytes', models.PositiveIntegerField()),
                ('parser_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='pending', max_length=16)),
                ('parser_version', models.CharField(blank=True, max_length=100)),
                ('parse_error', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_raw_data_records', to='audit.syncrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_data_records', to='audit.datasource')),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='RawDataObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_data_observations', to='audit.syncrun')),
                ('raw_data_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='audit.rawdatarecord')),
            ],
            options={
                'ordering': ('-observed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='rawdatarecord',
            index=models.Index(fields=['source', 'fetched_at'], name='audit_rawda_source__9c5f97_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatarecord',
            index=models.Index(fields=['parser_status', 'fetched_at'], name='audit_rawda_parser__292d64_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.UniqueConstraint(fields=('source', 'request_fingerprint', 'content_hash'), name='audit_raw_data_content_unique'),
        ),
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.CheckConstraint(condition=models.Q(('request_fingerprint__regex', '^[0-9a-f]{64}$'), ('content_hash__regex', '^[0-9a-f]{64}$')), name='audit_raw_data_hashes_valid'),
        ),
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.CheckConstraint(condition=models.Q(('payload_size_bytes', django.db.models.functions.text.Length('payload'))), name='audit_raw_data_payload_size_matches'),
        ),
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.CheckConstraint(condition=models.Q(('payload_size_bytes__lte', 1048576)), name='audit_raw_data_payload_size_limited'),
        ),
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.CheckConstraint(condition=models.Q(('http_status__isnull', True), models.Q(('http_status__gte', 100), ('http_status__lte', 599)), _connector='OR'), name='audit_raw_data_http_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parser_status', 'pending'), ('parser_version', ''), ('parse_error', '')), models.Q(('parser_status', 'parsed'), models.Q(('parser_version', ''), _negated=True), ('parse_error', '')), models.Q(('parser_status', 'failed'), models.Q(('parser_version', ''), _negated=True), models.Q(('parse_error', ''), _negated=True)), models.Q(('parser_status', 'unsupported'), models.Q(('parser_version', ''), _negated=True), ('parse_error', '')), _connector='OR'), name='audit_raw_data_parser_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='rawdataobservation',
            constraint=models.UniqueConstraint(fields=('sync_run', 'raw_data_record'), name='audit_raw_observation_run_record_unique'),
        ),
    ]
