# Generated by Django 5.2.16 on 2026-07-13 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rawdatarecord_rawdataobservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('company', 'Company'), ('security_listing', 'Security listing'), ('market_index', 'Market index'), ('index_membership', 'Index membership'), ('index_change_event', 'Index change event'), ('index_change_leg', 'Index change leg'), ('earnings_event', 'Earnings event'), ('earnings_date_change', 'Earnings date change'), ('filing', 'Filing'), ('filing_document', 'Filing document'), ('filing_earnings_link', 'Filing earnings link')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('raw_value', models.JSONField(blank=True, null=True)),
                ('normalized_value', models.JSONField(blank=True, null=True)),
                ('is_official', models.BooleanField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('observed_at', models.DateTimeField()),
                ('normalizer_version', models.CharField(max_length=100)),
                ('evidence_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_evidence_records', to='audit.rawdatarecord')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_evidence_records', to='audit.syncrun')),
            ],
            options={
                'ordering': ('-observed_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id', 'field_name', 'observed_at'], name='audit_sourc_target__647b1a_idx'), models.Index(fields=['raw_data_record', 'sync_run'], name='audit_sourc_raw_dat_11b965_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_type__in', ('company', 'security_listing', 'market_index', 'index_membership', 'index_change_event', 'index_change_leg', 'earnings_event', 'earnings_date_change', 'filing', 'filing_document', 'filing_earnings_link'))), name='audit_source_evidence_target_type_valid'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='audit_source_evidence_confidence_range'), models.CheckConstraint(condition=models.Q(('normalizer_version__regex', '[^[:space:]]')), name='audit_source_evidence_normalizer_not_empty'), models.CheckConstraint(condition=models.Q(('evidence_key__regex', '^[0-9a-f]{64}$')), name='audit_source_evidence_key_valid')],
            },
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "audit_sourceevidence" '
                'ADD CONSTRAINT "audit_source_evidence_observation_fk" '
                'FOREIGN KEY ("sync_run_id", "raw_data_record_id") '
                'REFERENCES "audit_rawdataobservation" '
                '("sync_run_id", "raw_data_record_id")'
            ),
            reverse_sql=(
                'ALTER TABLE "audit_sourceevidence" '
                'DROP CONSTRAINT "audit_source_evidence_observation_fk"'
            ),
        ),
    ]
