# Generated by Django 5.2.16 on 2026-07-13

import audit.security
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_rekey_source_evidence_by_raw_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="base_url",
            field=models.URLField(blank=True, validators=[audit.security.validate_safe_base_url]),
        ),
    ]
