# Generated by Django 5.2.16 on 2026-07-13 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_alter_datasource_base_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("deactivate", "Deactivate"),
                            ("manual_correction", "Manual correction"),
                            ("manual_sync", "Manual sync"),
                            ("retry", "Retry"),
                            ("login_sensitive_action", "Login-sensitive action"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("data_source", "Data source"),
                            ("sync_run", "Sync run"),
                            ("raw_data_record", "Raw data record"),
                            ("raw_data_observation", "Raw data observation"),
                            ("source_evidence", "Source evidence"),
                            ("data_change", "Data change"),
                            ("company", "Company"),
                            ("security_listing", "Security listing"),
                            ("market_index", "Market index"),
                            ("index_membership", "Index membership"),
                            ("index_change_event", "Index change event"),
                            ("index_change_leg", "Index change leg"),
                            ("earnings_event", "Earnings event"),
                            ("earnings_date_change", "Earnings date change"),
                            ("filing", "Filing"),
                            ("filing_document", "Filing document"),
                            ("filing_earnings_link", "Filing earnings link"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=2000)),
                ("request_id", models.CharField(max_length=255)),
                ("ip_hash", models.CharField(blank=True, max_length=67)),
                (
                    "audit_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_records",
                        to="audit.syncrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "action", "created_at"],
                        name="audit_audit_target__d7a77a_idx",
                    ),
                    models.Index(
                        fields=["actor_user", "created_at"],
                        name="audit_audit_actor_u_3a396d_idx",
                    ),
                    models.Index(
                        fields=["sync_run", "created_at"],
                        name="audit_audit_sync_ru_9a90a7_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                (
                                    "create",
                                    "update",
                                    "deactivate",
                                    "manual_correction",
                                    "manual_sync",
                                    "retry",
                                    "login_sensitive_action",
                                ),
                            )
                        ),
                        name="audit_record_action_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "target_type__in",
                                (
                                    "user",
                                    "data_source",
                                    "sync_run",
                                    "raw_data_record",
                                    "raw_data_observation",
                                    "source_evidence",
                                    "data_change",
                                    "company",
                                    "security_listing",
                                    "market_index",
                                    "index_membership",
                                    "index_change_event",
                                    "index_change_leg",
                                    "earnings_event",
                                    "earnings_date_change",
                                    "filing",
                                    "filing_document",
                                    "filing_earnings_link",
                                ),
                            )
                        ),
                        name="audit_record_target_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actor_user__isnull", False),
                                ("reason__regex", "[^[:space:]]"),
                            ),
                            models.Q(
                                ("actor_user__isnull", True),
                                ("sync_run__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="audit_record_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("request_id__regex", "[^[:space:]]")),
                        name="audit_record_request_id_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ip_hash", ""),
                            ("ip_hash__regex", "^v1:[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="audit_record_ip_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("audit_key__regex", "^[0-9a-f]{64}$")),
                        name="audit_record_key_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("security_listing", "Security listing"),
                            ("market_index", "Market index"),
                            ("index_membership", "Index membership"),
                            ("index_change_event", "Index change event"),
                            ("index_change_leg", "Index change leg"),
                            ("earnings_event", "Earnings event"),
                            ("earnings_date_change", "Earnings date change"),
                            ("filing", "Filing"),
                            ("filing_document", "Filing document"),
                            ("filing_earnings_link", "Filing earnings link"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=2000)),
                ("origin_key", models.CharField(max_length=255)),
                ("rule_version", models.CharField(max_length=100)),
                (
                    "change_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_changes",
                        to="audit.sourceevidence",
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_changes",
                        to="audit.syncrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-changed_at",),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "field_name", "changed_at"],
                        name="audit_datac_target__1441ff_idx",
                    ),
                    models.Index(
                        fields=["sync_run", "changed_at"],
                        name="audit_datac_sync_ru_9faa9c_idx",
                    ),
                    models.Index(
                        fields=["actor_user", "changed_at"],
                        name="audit_datac_actor_u_e8c1db_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "target_type__in",
                                (
                                    "company",
                                    "security_listing",
                                    "market_index",
                                    "index_membership",
                                    "index_change_event",
                                    "index_change_leg",
                                    "earnings_event",
                                    "earnings_date_change",
                                    "filing",
                                    "filing_document",
                                    "filing_earnings_link",
                                ),
                            )
                        ),
                        name="audit_data_change_target_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("field_name__regex", "[^[:space:]]")),
                        name="audit_data_change_field_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rule_version__regex", "[^[:space:]]")),
                        name="audit_data_change_rule_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("origin_key__regex", "[^[:space:]]")),
                        name="audit_data_change_origin_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("change_key__regex", "^[0-9a-f]{64}$")),
                        name="audit_data_change_key_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("old_value__isnull", True),
                                ("new_value__isnull", False),
                            ),
                            models.Q(
                                ("old_value__isnull", False),
                                ("new_value__isnull", True),
                            ),
                            models.Q(
                                ("old_value__isnull", False),
                                ("new_value__isnull", False),
                                models.Q(("old_value", models.F("new_value")), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="audit_data_change_values_differ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actor_user__isnull", False),
                                ("reason__regex", "[^[:space:]]"),
                            ),
                            models.Q(
                                ("actor_user__isnull", True),
                                models.Q(
                                    ("sync_run__isnull", False),
                                    ("source_evidence__isnull", False),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="audit_data_change_source_valid",
                    ),
                ],
            },
        ),
    ]
