# Generated by Django 5.2.16 on 2026-07-19 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auditrecord_datachange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataParseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('data_error', 'Data error'), ('system_error', 'System error'), ('unsupported', 'Unsupported')], max_length=16)),
                ('error_summary', models.CharField(blank=True, max_length=2000)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parse_attempts', to='audit.rawdataobservation')),
            ],
            options={
                'ordering': ('-finished_at',),
                'indexes': [models.Index(fields=['observation', 'parser_version'], name='audit_rawda_observa_127ad5_idx'), models.Index(fields=['status', 'finished_at'], name='audit_rawda_status_ef97e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('observation', 'parser_version'), name='audit_raw_parse_observation_parser_unique'), models.CheckConstraint(condition=models.Q(('parser_version__regex', '[^[:space:]]')), name='audit_raw_parse_parser_not_empty'), models.CheckConstraint(condition=models.Q(('finished_at__gte', models.F('started_at'))), name='audit_raw_parse_finish_after_start'), models.CheckConstraint(condition=models.Q(('status__in', ('succeeded', 'data_error', 'system_error', 'unsupported'))), name='audit_raw_parse_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), ('error_summary', '')), models.Q(('status__in', ('data_error', 'system_error', 'unsupported')), ('error_summary__regex', '[^[:space:]]')), _connector='OR'), name='audit_raw_parse_error_consistent')],
            },
        ),
    ]
