# Generated by Django 5.2.16 on 2026-09-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_extend_audit_targets_for_reconciliation_decision'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syncrun',
            name='audit_sync_run_counts_non_negative',
        ),
        migrations.AddField(
            model_name='syncrun',
            name='replay_contract_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='replay_input_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='replay_source_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replay_runs', to='audit.syncrun'),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='replayed_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='run_mode',
            field=models.CharField(choices=[('ingestion', 'Ingestion'), ('replay', 'Offline replay')], default='ingestion', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('run_mode', 'replay')), fields=('source', 'job_type', 'replay_source_sync_run', 'parser_version', 'replay_contract_version', 'replay_input_digest'), name='audit_sync_run_replay_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.CheckConstraint(condition=models.Q(('fetched_count__gte', 0), ('replayed_count__gte', 0), ('created_count__gte', 0), ('updated_count__gte', 0), ('skipped_count__gte', 0), ('failed_count__gte', 0)), name='audit_sync_run_counts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.CheckConstraint(condition=models.Q(('run_mode__in', ('ingestion', 'replay'))), name='audit_sync_run_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('run_mode', 'ingestion'), models.Q(('scope__window_kind__isnull', True), models.Q(('scope__window_kind', 'replay'), _negated=True), _connector='OR'), ('replay_source_sync_run__isnull', True), ('replay_contract_version', ''), ('replay_input_digest', ''), ('replayed_count', 0)), models.Q(('run_mode', 'replay'), ('scope__window_kind', 'replay'), ('replay_source_sync_run__isnull', False), ('replay_contract_version__regex', '[^[:space:]]'), ('replay_input_digest__regex', '^[0-9a-f]{64}$'), ('parser_version__regex', '[^[:space:]]'), ('fetched_count', 0)), _connector='OR'), name='audit_sync_run_replay_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.CheckConstraint(condition=models.Q(('replay_source_sync_run__isnull', True), models.Q(('pk', models.F('replay_source_sync_run')), _negated=True), _connector='OR'), name='audit_sync_run_replay_source_not_self'),
        ),
    ]
