# Generated by Django 5.2.16 on 2026-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_syncrun_offline_replay_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='provider_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
