# Generated by Django 5.2.16 on 2026-10-01 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_remove_auditrecord_audit_record_target_type_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditrecord',
            name='audit_record_target_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='datachange',
            name='audit_data_change_target_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='sourceevidence',
            name='audit_source_evidence_target_type_valid',
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='target_type',
            field=models.CharField(choices=[('user', 'User'), ('data_source', 'Data source'), ('sync_run', 'Sync run'), ('raw_data_record', 'Raw data record'), ('raw_data_observation', 'Raw data observation'), ('source_evidence', 'Source evidence'), ('data_change', 'Data change'), ('company', 'Company'), ('security_listing', 'Security listing'), ('market_index', 'Market index'), ('index_membership', 'Index membership'), ('index_change_event', 'Index change event'), ('index_change_leg', 'Index change leg'), ('earnings_event', 'Earnings event'), ('earnings_date_change', 'Earnings date change'), ('earnings_reconciliation_decision', 'Earnings reconciliation decision'), ('filing', 'Filing'), ('filing_document', 'Filing document'), ('filing_earnings_link', 'Filing earnings link'), ('filing_earnings_decision', 'Filing earnings decision'), ('investor_relations_observation', 'Investor relations observation'), ('investor_relations_decision', 'Investor relations decision')], max_length=32),
        ),
        migrations.AlterField(
            model_name='datachange',
            name='target_type',
            field=models.CharField(choices=[('company', 'Company'), ('security_listing', 'Security listing'), ('market_index', 'Market index'), ('index_membership', 'Index membership'), ('index_change_event', 'Index change event'), ('index_change_leg', 'Index change leg'), ('earnings_event', 'Earnings event'), ('earnings_date_change', 'Earnings date change'), ('filing', 'Filing'), ('filing_document', 'Filing document'), ('filing_earnings_link', 'Filing earnings link'), ('filing_earnings_decision', 'Filing earnings decision'), ('investor_relations_observation', 'Investor relations observation'), ('investor_relations_decision', 'Investor relations decision')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sourceevidence',
            name='target_type',
            field=models.CharField(choices=[('company', 'Company'), ('security_listing', 'Security listing'), ('market_index', 'Market index'), ('index_membership', 'Index membership'), ('index_change_event', 'Index change event'), ('index_change_leg', 'Index change leg'), ('earnings_event', 'Earnings event'), ('earnings_date_change', 'Earnings date change'), ('filing', 'Filing'), ('filing_document', 'Filing document'), ('filing_earnings_link', 'Filing earnings link'), ('filing_earnings_decision', 'Filing earnings decision'), ('investor_relations_observation', 'Investor relations observation'), ('investor_relations_decision', 'Investor relations decision')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='auditrecord',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ('user', 'data_source', 'sync_run', 'raw_data_record', 'raw_data_observation', 'source_evidence', 'data_change', 'company', 'security_listing', 'market_index', 'index_membership', 'index_change_event', 'index_change_leg', 'earnings_event', 'earnings_date_change', 'earnings_reconciliation_decision', 'filing', 'filing_document', 'filing_earnings_link', 'filing_earnings_decision', 'investor_relations_observation', 'investor_relations_decision'))), name='audit_record_target_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='datachange',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ('company', 'security_listing', 'market_index', 'index_membership', 'index_change_event', 'index_change_leg', 'earnings_event', 'earnings_date_change', 'filing', 'filing_document', 'filing_earnings_link', 'filing_earnings_decision', 'investor_relations_observation', 'investor_relations_decision'))), name='audit_data_change_target_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='sourceevidence',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ('company', 'security_listing', 'market_index', 'index_membership', 'index_change_event', 'index_change_leg', 'earnings_event', 'earnings_date_change', 'filing', 'filing_document', 'filing_earnings_link', 'filing_earnings_decision', 'investor_relations_observation', 'investor_relations_decision'))), name='audit_source_evidence_target_type_valid'),
        ),
    ]
