# Generated by Django 5.2.16 on 2026-07-14 02:57

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
from django.db import migrations, models

import audit.security


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audit", "0006_auditrecord_datachange"),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("cik", models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                (
                    "issuer_type",
                    models.CharField(
                        choices=[
                            ("domestic", "Domestic"),
                            ("foreign_private", "Foreign private issuer"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("fiscal_year_end_month_day", models.CharField(blank=True, max_length=5)),
                (
                    "investor_relations_url",
                    models.URLField(blank=True, validators=[audit.security.validate_safe_base_url]),
                ),
                (
                    "monitoring_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending_identity", "Pending identity"),
                        ],
                        default="pending_identity",
                        max_length=32,
                    ),
                ),
                ("monitoring_recalculated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_name", "id"),
                "indexes": [
                    models.Index(fields=["legal_name"], name="companies_c_legal_n_12d6ea_idx"),
                    models.Index(fields=["display_name"], name="companies_c_display_39c330_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cik__isnull", True), ("cik__regex", "^[0-9]{10}$"), _connector="OR"
                        ),
                        name="companies_company_cik_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("country_code", ""),
                            ("country_code__regex", "^[A-Z]{2}$"),
                            _connector="OR",
                        ),
                        name="companies_company_country_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fiscal_year_end_month_day", ""),
                            (
                                "fiscal_year_end_month_day__regex",
                                "^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$",
                            ),
                            _connector="OR",
                        ),
                        name="companies_company_fiscal_end_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("legal_name__regex", "[^[:space:]]"),
                            ("display_name__regex", "[^[:space:]]"),
                        ),
                        name="companies_company_names_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("issuer_type__in", ("domestic", "foreign_private", "other", "unknown"))
                        ),
                        name="companies_company_issuer_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("monitoring_status__in", ("active", "inactive", "pending_identity"))
                        ),
                        name="companies_company_monitoring_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ticker", models.CharField(max_length=32)),
                ("exchange", models.CharField(max_length=32)),
                ("security_name", models.CharField(blank=True, max_length=255)),
                ("security_type", models.CharField(default="unknown", max_length=64)),
                ("share_class", models.CharField(blank=True, max_length=32)),
                ("is_primary", models.BooleanField(default=False)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_listings",
                        to="companies.company",
                    ),
                ),
                (
                    "source_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_listings",
                        to="audit.sourceevidence",
                    ),
                ),
            ],
            options={
                "ordering": ("exchange", "ticker", "effective_from", "id"),
                "indexes": [
                    models.Index(
                        fields=["ticker", "exchange"], name="companies_s_ticker_cac416_idx"
                    ),
                    models.Index(
                        fields=["company", "effective_from"], name="companies_s_company_d8ff4d_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ticker__regex", "[^[:space:]]"),
                            ("exchange__regex", "[^[:space:]]"),
                            ("security_type__regex", "[^[:space:]]"),
                        ),
                        name="companies_listing_identity_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="companies_listing_date_order_valid",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=(
                            ("exchange", "="),
                            ("ticker", "="),
                            (
                                models.Func(
                                    models.F("effective_from"),
                                    models.F("effective_to"),
                                    models.Value("[)"),
                                    function="DATERANGE",
                                    output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                                ),
                                "&&",
                            ),
                        ),
                        name="companies_listing_exchange_ticker_no_overlap",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("is_primary", True)),
                        expressions=(
                            ("company", "="),
                            (
                                models.Func(
                                    models.F("effective_from"),
                                    models.F("effective_to"),
                                    models.Value("[)"),
                                    function="DATERANGE",
                                    output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                                ),
                                "&&",
                            ),
                        ),
                        name="companies_listing_primary_no_overlap",
                    ),
                ],
            },
        ),
    ]
