# Generated by Django 5.2.16 on 2026-07-14 09:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('index_group', models.CharField(choices=[('LARGE', 'Large-cap index'), ('SMALL', 'Small-cap index')], max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['index_group'], name='indexes_mar_index_g_323595_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', frozenset(['DJIA', 'NASDAQ100', 'RUSSELL2000', 'SP500'])), ('code__regex', '[^[:space:]]')), name='indexes_market_index_code_valid'), models.CheckConstraint(condition=models.Q(('name__regex', '[^[:space:]]')), name='indexes_market_index_name_not_blank'), models.CheckConstraint(condition=models.Q(('index_group__in', frozenset(['LARGE', 'SMALL']))), name='indexes_market_index_group_valid'), models.CheckConstraint(condition=models.Q(models.Q(('code', 'SP500'), ('index_group', 'LARGE')), models.Q(('code', 'NASDAQ100'), ('index_group', 'LARGE')), models.Q(('code', 'DJIA'), ('index_group', 'LARGE')), models.Q(('code', 'RUSSELL2000'), ('index_group', 'SMALL')), _connector='OR'), name='indexes_market_index_code_group_consistent')],
            },
        ),
    ]
