# Generated by Django 5.2.16 on 2026-07-14 11:06

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auditrecord_datachange'),
        ('companies', '0001_initial'),
        ('indexes', '0002_seed_builtin_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('announced', 'Announced'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('corrected', 'Corrected')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='indexes.marketindex')),
                ('security_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_memberships', to='companies.securitylisting')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='index_memberships', to='audit.sourceevidence')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='indexes.indexmembership')),
            ],
            options={
                'ordering': ('security_listing', 'index', 'effective_from', 'id'),
                'indexes': [models.Index(fields=['index', 'effective_from'], name='indexes_ind_index_i_67fa34_idx'), models.Index(fields=['security_listing', 'effective_from'], name='indexes_ind_securit_283b56_idx'), models.Index(fields=['status', 'effective_from'], name='indexes_ind_status_97f7fa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('announced', 'active', 'ended', 'cancelled', 'corrected'))), name='indexes_membership_status_valid'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='indexes_membership_date_order_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ended'), _negated=True), ('effective_to__isnull', False), _connector='OR'), name='indexes_membership_ended_has_end_date'), models.CheckConstraint(condition=models.Q(('announcement_date__isnull', True), ('announcement_date__lte', models.F('effective_from')), _connector='OR'), name='indexes_membership_announcement_not_after_start'), models.UniqueConstraint(condition=models.Q(('status__in', ('announced', 'active', 'ended'))), fields=('index', 'security_listing', 'effective_from'), name='indexes_membership_normative_identity_unique'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('announced', 'active', 'ended'))), expressions=(('security_listing', '='), ('index', '='), (models.Func(models.F('effective_from'), models.F('effective_to'), models.Value('[)'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')), name='indexes_membership_normative_no_overlap')],
            },
        ),
    ]
