# Generated by Django 5.2.16 on 2026-07-14 11:06

from django.db import migrations

CREATE_MEMBERSHIP_TRIGGER_FUNCTION = r"""
CREATE OR REPLACE FUNCTION check_membership_within_listing()
RETURNS TRIGGER AS $$
DECLARE
    current_row RECORD;
    listing RECORD;
BEGIN
    SELECT status, security_listing_id, effective_from, effective_to
      INTO current_row
      FROM indexes_indexmembership
     WHERE id = NEW.id;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    IF current_row.status NOT IN ('announced', 'active', 'ended') THEN
        RETURN NEW;
    END IF;

    SELECT effective_from, effective_to
      INTO listing
      FROM companies_securitylisting
     WHERE id = current_row.security_listing_id
       FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'SecurityListing not found for membership %', NEW.id
        USING ERRCODE = '23514';
    END IF;

    IF current_row.effective_from < listing.effective_from THEN
        RAISE EXCEPTION
            'Membership % effective_from % is before listing effective_from %',
            NEW.id, current_row.effective_from, listing.effective_from
        USING ERRCODE = '23514';
    END IF;

    IF listing.effective_to IS NOT NULL AND (
        current_row.effective_to IS NULL
        OR current_row.effective_to > listing.effective_to
    ) THEN
        RAISE EXCEPTION
            'Membership % effective_to % exceeds listing effective_to %',
            NEW.id, current_row.effective_to, listing.effective_to
        USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CREATE_MEMBERSHIP_TRIGGER = """
CREATE CONSTRAINT TRIGGER trg_membership_within_listing
    AFTER INSERT OR UPDATE ON indexes_indexmembership
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION check_membership_within_listing();
"""

DROP_MEMBERSHIP_TRIGGER = """
DROP TRIGGER IF EXISTS trg_membership_within_listing ON indexes_indexmembership;
"""

DROP_MEMBERSHIP_FUNCTION = """
DROP FUNCTION IF EXISTS check_membership_within_listing();
"""

CREATE_LISTING_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION check_listing_boundaries_memberships()
RETURNS TRIGGER AS $$
DECLARE
    current_listing RECORD;
    violating UUID;
BEGIN
    SELECT effective_from, effective_to
      INTO current_listing
      FROM companies_securitylisting
     WHERE id = NEW.id
       FOR UPDATE;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    SELECT im.id INTO violating
      FROM indexes_indexmembership im
     WHERE im.security_listing_id = NEW.id
       AND im.status IN ('announced', 'active', 'ended')
       AND (
           im.effective_from < current_listing.effective_from
           OR (
               current_listing.effective_to IS NOT NULL
               AND (
                   im.effective_to IS NULL
                   OR im.effective_to > current_listing.effective_to
               )
           )
       )
     LIMIT 1;

    IF violating IS NOT NULL THEN
        RAISE EXCEPTION
            'Listing % boundary change violates membership %',
            NEW.id, violating
        USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CREATE_LISTING_TRIGGER = """
CREATE CONSTRAINT TRIGGER trg_listing_boundaries_memberships
    AFTER UPDATE OF effective_from, effective_to ON companies_securitylisting
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION check_listing_boundaries_memberships();
"""

DROP_LISTING_TRIGGER = """
DROP TRIGGER IF EXISTS trg_listing_boundaries_memberships ON companies_securitylisting;
"""

DROP_LISTING_FUNCTION = """
DROP FUNCTION IF EXISTS check_listing_boundaries_memberships();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("indexes", "0003_index_membership"),
        ("companies", "0001_initial"),
    ]

    operations = [
        # Membership-side trigger
        migrations.RunSQL(
            sql=CREATE_MEMBERSHIP_TRIGGER_FUNCTION + "\n" + CREATE_MEMBERSHIP_TRIGGER,
            reverse_sql=DROP_MEMBERSHIP_TRIGGER + "\n" + DROP_MEMBERSHIP_FUNCTION,
        ),
        # SecurityListing-side trigger
        migrations.RunSQL(
            sql=CREATE_LISTING_TRIGGER_FUNCTION + "\n" + CREATE_LISTING_TRIGGER,
            reverse_sql=DROP_LISTING_TRIGGER + "\n" + DROP_LISTING_FUNCTION,
        ),
    ]
