# Generated by Django 5.2.16 on 2026-07-19 08:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_raw_data_parse_attempt'),
        ('companies', '0001_initial'),
        ('indexes', '0004_constraint_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('corrected', 'Corrected')], default='active', max_length=16)),
                ('displacement', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('cross_index', 'Cross Index'), ('none', 'None')], default='none', max_length=16)),
                ('monitoring_impact', models.CharField(choices=[('continues', 'Continues'), ('enters_base_pool', 'Enters Base Pool'), ('exits_base_pool', 'Exits Base Pool'), ('reenters_base_pool', 'Reenters Base Pool')], default='continues', max_length=20)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='companies.company')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='audit.sourceevidence')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='indexes.indexchangeevent')),
            ],
            options={
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='IndexChangeLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=8)),
                ('effective_date', models.DateField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='indexes.indexchangeevent')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_legs', to='indexes.marketindex')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_legs', to='indexes.indexmembership')),
                ('security_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_legs', to='companies.securitylisting')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_legs', to='audit.sourceevidence')),
            ],
            options={
                'ordering': ('-effective_date', 'index', 'security_listing'),
            },
        ),
        migrations.AddIndex(
            model_name='indexchangeevent',
            index=models.Index(fields=['company', 'effective_date'], name='indexes_ind_company_bd63ac_idx'),
        ),
        migrations.AddIndex(
            model_name='indexchangeevent',
            index=models.Index(fields=['status', 'effective_date'], name='indexes_ind_status_728e65_idx'),
        ),
        migrations.AddIndex(
            model_name='indexchangeevent',
            index=models.Index(fields=['displacement', 'effective_date'], name='indexes_ind_displac_d68ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='indexchangeevent',
            index=models.Index(fields=['monitoring_impact', 'effective_date'], name='indexes_ind_monitor_8bb13e_idx'),
        ),
        migrations.AddConstraint(
            model_name='indexchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'cancelled', 'corrected'))), name='indexes_change_event_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='indexchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(('displacement__in', ('upgrade', 'downgrade', 'cross_index', 'none'))), name='indexes_change_event_displacement_valid'),
        ),
        migrations.AddConstraint(
            model_name='indexchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(('monitoring_impact__in', ('continues', 'enters_base_pool', 'exits_base_pool', 'reenters_base_pool'))), name='indexes_change_event_monitoring_valid'),
        ),
        migrations.AddConstraint(
            model_name='indexchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(('announcement_date__isnull', True), ('announcement_date__lte', models.F('effective_date')), _connector='OR'), name='indexes_change_event_announcement_not_after_effective'),
        ),
        migrations.AddIndex(
            model_name='indexchangeleg',
            index=models.Index(fields=['index', 'effective_date'], name='indexes_ind_index_i_9b84ab_idx'),
        ),
        migrations.AddIndex(
            model_name='indexchangeleg',
            index=models.Index(fields=['security_listing', 'effective_date'], name='indexes_ind_securit_337d60_idx'),
        ),
        migrations.AddIndex(
            model_name='indexchangeleg',
            index=models.Index(fields=['action', 'effective_date'], name='indexes_ind_action_37f8a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='indexchangeleg',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('added', 'removed'))), name='indexes_change_leg_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='indexchangeleg',
            constraint=models.UniqueConstraint(fields=('event', 'index', 'security_listing', 'action'), name='indexes_change_leg_action_unique_per_event'),
        ),
    ]
