# Generated by Django 5.2.16 on 2026-07-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0005_index_change_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indexchangeevent',
            name='indexes_change_event_announcement_not_after_effective',
        ),
    ]
