# Generated by Django 5.2.16 on 2026-07-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_raw_data_parse_attempt'),
        ('companies', '0001_initial'),
        ('indexes', '0006_fix_event_announcement_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indexchangeevent',
            constraint=models.UniqueConstraint(fields=('company', 'effective_date'), name='indexes_change_event_company_date_unique'),
        ),
    ]
