# Generated by Django 5.2.16 on 2026-07-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_raw_data_parse_attempt'),
        ('companies', '0001_initial'),
        ('indexes', '0007_add_event_company_date_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indexchangeevent',
            name='indexes_change_event_company_date_unique',
        ),
        migrations.RemoveField(
            model_name='indexchangeevent',
            name='announcement_date',
        ),
        migrations.AddField(
            model_name='indexchangeleg',
            name='announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='indexchangeevent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('company', 'effective_date'), name='indexes_change_event_active_company_date_unique'),
        ),
    ]
