# Generated by Django 5.2.16 on 2026-07-19 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0008_fix_step2_correctness_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexChangeCorrelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('displacement', models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('cross_index', 'Cross Index'), ('none', 'None')], max_length=16, null=True)),
                ('monitoring_impact', models.CharField(blank=True, choices=[('continues', 'Continues'), ('enters_base_pool', 'Enters Base Pool'), ('exits_base_pool', 'Exits Base Pool'), ('reenters_base_pool', 'Reenters Base Pool')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earlier_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correlations_as_earlier', to='indexes.indexchangeevent')),
                ('later_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correlations_as_later', to='indexes.indexchangeevent')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'confirmed', 'rejected'))), name='indexes_correlation_status_valid'), models.CheckConstraint(condition=models.Q(('earlier_event', models.F('later_event')), _negated=True), name='indexes_correlation_not_self'), models.UniqueConstraint(fields=('earlier_event', 'later_event'), name='indexes_correlation_pair_unique')],
            },
        ),
    ]
