# Generated by Django 5.2.16 on 2026-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0009_add_index_change_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexchangecorrelation',
            name='displacement',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('cross_index', 'Cross Index'), ('none', 'None')], max_length=16),
        ),
        migrations.AlterField(
            model_name='indexchangecorrelation',
            name='monitoring_impact',
            field=models.CharField(blank=True, choices=[('continues', 'Continues'), ('enters_base_pool', 'Enters Base Pool'), ('exits_base_pool', 'Exits Base Pool'), ('reenters_base_pool', 'Reenters Base Pool')], max_length=20),
        ),
    ]
