# Generated by Django 5.2.16 on 2026-07-19 17:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audit", "0007_raw_data_parse_attempt"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "identity_status",
                    models.CharField(
                        choices=[("candidate", "Candidate"), ("canonical", "Canonical")],
                        default="candidate",
                        max_length=16,
                    ),
                ),
                (
                    "identity_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="SHA-256 canonical identity hash; NULL for CANDIDATE events.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identity_rule_version",
                    models.CharField(
                        blank=True,
                        help_text="Rule version used to derive identity_key.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "period_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Fiscal period end date; required for CANONICAL events.",
                        null=True,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("FY", "FY"),
                            ("H1", "H1"),
                            ("H2", "H2"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Required for CANONICAL events.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "includes_q4",
                    models.BooleanField(
                        default=False,
                        help_text="Always true for FY; always false for Q1/Q2/Q3/H1/H2/OTHER.",
                    ),
                ),
                (
                    "fiscal_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Display/presentation attribute; not part of canonical identity.",
                        null=True,
                    ),
                ),
                (
                    "fiscal_calendar_type",
                    models.CharField(
                        choices=[
                            ("month_based", "Month-based"),
                            ("week_based_52_53", "52/53-week"),
                            ("other", "Other"),
                        ],
                        default="month_based",
                        max_length=20,
                    ),
                ),
                (
                    "period_length_weeks",
                    models.IntegerField(
                        blank=True,
                        help_text="Required (52 or 53) when fiscal_calendar_type is week_based_52_53.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled_estimated", "Scheduled (Estimated)"),
                            ("scheduled_confirmed", "Scheduled (Confirmed)"),
                            ("released", "Released"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled_estimated",
                        max_length=32,
                    ),
                ),
                ("estimated_release_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_release_at", models.DateTimeField(blank=True, null=True)),
                ("earnings_release_at", models.DateTimeField(blank=True, null=True)),
                ("conference_call_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_session",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pre_market", "Pre-market"),
                            ("after_market", "After-market"),
                            ("during_market", "During market"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings_events",
                        to="companies.company",
                    ),
                ),
                (
                    "source_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings_events",
                        to="audit.sourceevidence",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["company", "period_end_date"], name="earnings_ea_company_17097e_idx"
                    ),
                    models.Index(
                        fields=["status", "estimated_release_at"],
                        name="earnings_ea_status_f9962f_idx",
                    ),
                    models.Index(
                        fields=["status", "confirmed_release_at"],
                        name="earnings_ea_status_05223b_idx",
                    ),
                    models.Index(fields=["period_end_date"], name="earnings_ea_period__f3c8a3_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "period_type__in",
                                frozenset(["FY", "H1", "H2", "OTHER", "Q1", "Q2", "Q3"]),
                            ),
                            ("period_type__isnull", True),
                            _connector="OR",
                        ),
                        name="earnings_event_period_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                frozenset(
                                    [
                                        "cancelled",
                                        "released",
                                        "scheduled_confirmed",
                                        "scheduled_estimated",
                                    ]
                                ),
                            )
                        ),
                        name="earnings_event_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("identity_status__in", frozenset(["candidate", "canonical"]))
                        ),
                        name="earnings_event_identity_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "fiscal_calendar_type__in",
                                frozenset(["month_based", "other", "week_based_52_53"]),
                            )
                        ),
                        name="earnings_event_calendar_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "release_session__in",
                                frozenset(
                                    ["after_market", "during_market", "pre_market", "unknown"]
                                ),
                            ),
                            ("release_session__isnull", True),
                            _connector="OR",
                        ),
                        name="earnings_event_release_session_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("includes_q4", True), ("period_type", "FY")),
                            models.Q(
                                models.Q(("period_type", "FY"), _negated=True),
                                ("includes_q4", False),
                            ),
                            _connector="OR",
                        ),
                        name="earnings_event_includes_q4_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("fiscal_calendar_type", "week_based_52_53"), _negated=True),
                            ("period_length_weeks__in", (52, 53)),
                            _connector="OR",
                        ),
                        name="earnings_event_week_length_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fiscal_calendar_type", "week_based_52_53"),
                            ("period_length_weeks__isnull", True),
                            _connector="OR",
                        ),
                        name="earnings_event_week_length_null",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("identity_status", "canonical"), _negated=True),
                            models.Q(
                                ("period_end_date__isnull", False),
                                ("period_type__isnull", False),
                                ("identity_key__isnull", False),
                                ("identity_rule_version__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="earnings_event_canonical_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("identity_status", "candidate"), _negated=True),
                            ("identity_key__isnull", True),
                            _connector="OR",
                        ),
                        name="earnings_event_candidate_key_null",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("identity_status", "candidate"), _negated=True),
                            ("identity_rule_version__isnull", True),
                            _connector="OR",
                        ),
                        name="earnings_event_candidate_version_null",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("identity_status", "canonical")),
                        fields=("company", "period_end_date", "period_type"),
                        name="earnings_event_canonical_business_unique",
                    ),
                ],
            },
        ),
    ]
