# Generated by Django 5.2.16 on 2026-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_raw_data_parse_attempt'),
        ('companies', '0001_initial'),
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='earningsevent',
            name='earnings_event_includes_q4_consistent',
        ),
        migrations.RemoveConstraint(
            model_name='earningsevent',
            name='earnings_event_week_length_valid',
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period_type__isnull', False), ('period_type', 'FY'), ('includes_q4', True)), models.Q(('includes_q4', False), models.Q(('period_type__isnull', True), models.Q(('period_type__isnull', False), models.Q(('period_type', 'FY'), _negated=True)), _connector='OR')), _connector='OR'), name='earnings_event_includes_q4_consistent'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fiscal_calendar_type', 'week_based_52_53'), _negated=True), models.Q(('period_length_weeks__isnull', False), ('period_length_weeks__in', (52, 53))), _connector='OR'), name='earnings_event_week_length_valid'),
        ),
    ]
