# Generated by Django 5.2.16 on 2026-09-19 09:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from typing import Any

from django.db import migrations, models


def backfill_schedule_precision(apps: Any, schema_editor: Any) -> None:
    EarningsEvent = apps.get_model("earnings", "EarningsEvent")
    for prefix in (
        "estimated_release",
        "confirmed_release",
        "earnings_release",
        "conference_call",
    ):
        EarningsEvent.objects.filter(**{f"{prefix}_at__isnull": False}).update(
            **{
                f"{prefix}_precision": "exact_datetime",
                f"{prefix}_date": None,
            }
        )
    EarningsEvent.objects.filter(release_session__isnull=True).update(
        release_session="unknown"
    )
    # Flush deferred FK checks before ALTER TABLE in the same migration transaction.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0007_raw_data_parse_attempt'),
        ('companies', '0001_initial'),
        ('earnings', '0002_fix_nullable_period_invariants'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsDateChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('estimated_release', 'Estimated release'), ('confirmed_release', 'Confirmed release'), ('earnings_release', 'Earnings release'), ('conference_call', 'Conference call'), ('release_session', 'Release session')], max_length=32)),
                ('change_kind', models.CharField(choices=[('value_change', 'Value change'), ('precision_refinement', 'Precision refinement'), ('precision_regression', 'Precision regression')], max_length=32)),
                ('old_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime'), ('session_only', 'Session only')], max_length=16)),
                ('new_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime'), ('session_only', 'Session only')], max_length=16)),
                ('old_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('old_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_datetime', models.DateTimeField(blank=True, null=True)),
                ('old_session', models.CharField(blank=True, choices=[('pre_market', 'Pre-market'), ('after_market', 'After-market'), ('during_market', 'During market'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('new_session', models.CharField(blank=True, choices=[('pre_market', 'Pre-market'), ('after_market', 'After-market'), ('during_market', 'During market'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-detected_at', '-created_at'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='earningsevent',
            name='earnings_event_release_session_valid',
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='conference_call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='conference_call_precision',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='confirmed_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='confirmed_release_precision',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='earnings_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='earnings_release_precision',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='estimated_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='estimated_release_precision',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16),
        ),
        migrations.RunPython(
            backfill_schedule_precision,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='earningsevent',
            name='release_session',
            field=models.CharField(choices=[('pre_market', 'Pre-market'), ('after_market', 'After-market'), ('during_market', 'During market'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddIndex(
            model_name='earningsevent',
            index=models.Index(fields=['status', 'estimated_release_date'], name='earnings_ea_status_424bea_idx'),
        ),
        migrations.AddIndex(
            model_name='earningsevent',
            index=models.Index(fields=['status', 'confirmed_release_date'], name='earnings_ea_status_8ca028_idx'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(('release_session__in', frozenset(['after_market', 'during_market', 'pre_market', 'unknown']))), name='earnings_event_release_session_valid'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estimated_release_at__isnull', True), ('estimated_release_date__isnull', True), ('estimated_release_precision', 'unknown')), models.Q(('estimated_release_at__isnull', True), ('estimated_release_date__isnull', False), ('estimated_release_precision', 'date_only')), models.Q(('estimated_release_at__isnull', False), ('estimated_release_date__isnull', True), ('estimated_release_precision', 'exact_datetime')), _connector='OR'), name='earnings_event_estimated_release_precision_consistent'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_release_at__isnull', True), ('confirmed_release_date__isnull', True), ('confirmed_release_precision', 'unknown')), models.Q(('confirmed_release_at__isnull', True), ('confirmed_release_date__isnull', False), ('confirmed_release_precision', 'date_only')), models.Q(('confirmed_release_at__isnull', False), ('confirmed_release_date__isnull', True), ('confirmed_release_precision', 'exact_datetime')), _connector='OR'), name='earnings_event_confirmed_release_precision_consistent'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('earnings_release_at__isnull', True), ('earnings_release_date__isnull', True), ('earnings_release_precision', 'unknown')), models.Q(('earnings_release_at__isnull', True), ('earnings_release_date__isnull', False), ('earnings_release_precision', 'date_only')), models.Q(('earnings_release_at__isnull', False), ('earnings_release_date__isnull', True), ('earnings_release_precision', 'exact_datetime')), _connector='OR'), name='earnings_event_earnings_release_precision_consistent'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conference_call_at__isnull', True), ('conference_call_date__isnull', True), ('conference_call_precision', 'unknown')), models.Q(('conference_call_at__isnull', True), ('conference_call_date__isnull', False), ('conference_call_precision', 'date_only')), models.Q(('conference_call_at__isnull', False), ('conference_call_date__isnull', True), ('conference_call_precision', 'exact_datetime')), _connector='OR'), name='earnings_event_conference_call_precision_consistent'),
        ),
        migrations.AddField(
            model_name='earningsdatechange',
            name='data_change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_date_change', to='audit.datachange'),
        ),
        migrations.AddField(
            model_name='earningsdatechange',
            name='earnings_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='date_changes', to='earnings.earningsevent'),
        ),
        migrations.AddIndex(
            model_name='earningsdatechange',
            index=models.Index(fields=['earnings_event', 'detected_at'], name='earnings_ea_earning_b33541_idx'),
        ),
        migrations.AddIndex(
            model_name='earningsdatechange',
            index=models.Index(fields=['field_name', 'change_kind', 'detected_at'], name='earnings_ea_field_n_787d27_idx'),
        ),
        migrations.AddConstraint(
            model_name='earningsdatechange',
            constraint=models.CheckConstraint(condition=models.Q(('field_name__in', frozenset(['conference_call', 'confirmed_release', 'earnings_release', 'estimated_release', 'release_session']))), name='earnings_date_change_field_valid'),
        ),
        migrations.AddConstraint(
            model_name='earningsdatechange',
            constraint=models.CheckConstraint(condition=models.Q(('change_kind__in', frozenset(['precision_refinement', 'precision_regression', 'value_change']))), name='earnings_date_change_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='earningsdatechange',
            constraint=models.CheckConstraint(condition=models.Q(('old_precision__in', frozenset(['date_only', 'exact_datetime', 'session_only', 'unknown'])), ('new_precision__in', frozenset(['date_only', 'exact_datetime', 'session_only', 'unknown']))), name='earnings_date_change_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='earningsdatechange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('field_name', 'release_session'), ('old_precision', 'session_only'), ('new_precision', 'session_only'), ('old_date__isnull', True), ('new_date__isnull', True), ('old_datetime__isnull', True), ('new_datetime__isnull', True), ('old_session__isnull', False), ('new_session__isnull', False)), models.Q(models.Q(('field_name', 'release_session'), _negated=True), models.Q(models.Q(('old_date__isnull', True), ('old_datetime__isnull', True), ('old_precision', 'unknown')), models.Q(('old_date__isnull', False), ('old_datetime__isnull', True), ('old_precision', 'date_only')), models.Q(('old_date__isnull', True), ('old_datetime__isnull', False), ('old_precision', 'exact_datetime')), _connector='OR'), models.Q(models.Q(('new_date__isnull', True), ('new_datetime__isnull', True), ('new_precision', 'unknown')), models.Q(('new_date__isnull', False), ('new_datetime__isnull', True), ('new_precision', 'date_only')), models.Q(('new_date__isnull', True), ('new_datetime__isnull', False), ('new_precision', 'exact_datetime')), _connector='OR'), ('old_session__isnull', True), ('new_session__isnull', True)), _connector='OR'), name='earnings_date_change_value_shape_valid'),
        ),
    ]
