# Generated by Django 5.2.16 on 2026-09-20 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_raw_data_parse_attempt'),
        ('earnings', '0003_earningsdatechange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsCalendarObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=64)),
                ('provider_version', models.CharField(max_length=100)),
                ('parser_version', models.CharField(max_length=100)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('raw_position', models.PositiveIntegerField()),
                ('cik', models.CharField(blank=True, max_length=10)),
                ('ticker', models.CharField(blank=True, max_length=32)),
                ('exchange', models.CharField(blank=True, max_length=32)),
                ('provider_symbol', models.CharField(blank=True, max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('fiscal_label_raw', models.CharField(blank=True, max_length=64)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('period_type', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('FY', 'FY'), ('H1', 'H1'), ('H2', 'H2'), ('OTHER', 'Other')], max_length=8, null=True)),
                ('fiscal_calendar_type', models.CharField(blank=True, choices=[('month_based', 'Month-based'), ('week_based_52_53', '52/53-week'), ('other', 'Other')], max_length=20, null=True)),
                ('period_length_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_release_date', models.DateField(blank=True, null=True)),
                ('estimated_release_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_release_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16)),
                ('release_session', models.CharField(choices=[('pre_market', 'Pre-market'), ('after_market', 'After-market'), ('during_market', 'During market'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('source_observed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_calendar_observations', to='audit.rawdatarecord')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_calendar_observations', to='audit.datasource')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['source', 'provider_event_id'], name='earnings_ea_source__56b806_idx')],
                'constraints': [models.UniqueConstraint(fields=('raw_data_record', 'parser_version', 'provider_event_id'), name='earnings_calendar_observation_record_parser_event_unique'), models.CheckConstraint(condition=models.Q(('provider_key__regex', '^[a-z][a-z0-9._-]{1,63}$')), name='earnings_calendar_observation_provider_key_valid'), models.CheckConstraint(condition=models.Q(('provider_version__regex', '[^[:space:]]'), ('parser_version__regex', '[^[:space:]]'), ('provider_event_id__regex', '[^[:space:]]')), name='earnings_calendar_observation_identity_not_blank'), models.CheckConstraint(condition=models.Q(('cik', ''), ('cik__regex', '^[0-9]{10}$'), _connector='OR'), name='earnings_calendar_observation_cik_valid'), models.CheckConstraint(condition=models.Q(('period_type__isnull', True), ('period_type__in', frozenset(['FY', 'H1', 'H2', 'OTHER', 'Q1', 'Q2', 'Q3'])), _connector='OR'), name='earnings_calendar_observation_period_type_valid'), models.CheckConstraint(condition=models.Q(('fiscal_calendar_type__isnull', True), ('fiscal_calendar_type__in', frozenset(['month_based', 'other', 'week_based_52_53'])), _connector='OR'), name='earnings_calendar_observation_calendar_type_valid'), models.CheckConstraint(condition=models.Q(('release_session__in', frozenset(['after_market', 'during_market', 'pre_market', 'unknown']))), name='earnings_calendar_observation_release_session_valid'), models.CheckConstraint(condition=models.Q(models.Q(('estimated_release_at__isnull', True), ('estimated_release_date__isnull', True), ('estimated_release_precision', 'unknown')), models.Q(('estimated_release_at__isnull', True), ('estimated_release_date__isnull', False), ('estimated_release_precision', 'date_only')), models.Q(('estimated_release_at__isnull', False), ('estimated_release_date__isnull', True), ('estimated_release_precision', 'exact_datetime')), _connector='OR'), name='earnings_calendar_observation_estimated_precision_valid'), models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='earnings_calendar_observation_confidence_range')],
            },
        ),
    ]
