# Generated by Django 5.2.16 on 2026-09-20 04:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0008_extend_audit_targets_for_reconciliation_decision"),
        ("earnings", "0004_earningscalendarobservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningsReconciliationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("created_candidate", "Created candidate"),
                            ("matched_candidate", "Matched candidate"),
                            ("matched_canonical", "Matched canonical"),
                            ("duplicate_of", "Duplicate of"),
                            ("collision", "Collision"),
                            ("conflict", "Conflict"),
                            ("review_required", "Review required"),
                            ("no_match", "No match"),
                            ("ignored", "Ignored"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("covered_fields", models.JSONField(blank=True, default=list)),
                ("rule_version", models.CharField(max_length=100)),
                ("match_factors", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, max_length=2000)),
                ("request_id", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decision_key", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings_reconciliation_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_decisions",
                        to="earnings.earningscalendarobservation",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_decisions",
                        to="earnings.earningsreconciliationdecision",
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings_reconciliation_decisions",
                        to="audit.syncrun",
                    ),
                ),
                (
                    "target_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_decisions",
                        to="earnings.earningsevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-decided_at", "-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["observation", "decided_at"], name="earnings_ea_observa_fdf824_idx"
                    ),
                    models.Index(
                        fields=["decision_type", "status", "decided_at"],
                        name="earnings_ea_decisio_03e5dc_idx",
                    ),
                    models.Index(
                        fields=["target_event", "decided_at"], name="earnings_ea_target__cfb583_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "decision_type__in",
                                frozenset(
                                    [
                                        "collision",
                                        "conflict",
                                        "created_candidate",
                                        "duplicate_of",
                                        "ignored",
                                        "matched_candidate",
                                        "matched_canonical",
                                        "no_match",
                                        "review_required",
                                    ]
                                ),
                            )
                        ),
                        name="earnings_reconciliation_decision_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", frozenset(["open", "rejected", "resolved"]))
                        ),
                        name="earnings_reconciliation_decision_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "resolved"),
                                (
                                    "decision_type__in",
                                    frozenset(
                                        [
                                            "created_candidate",
                                            "duplicate_of",
                                            "matched_candidate",
                                            "matched_canonical",
                                        ]
                                    ),
                                ),
                                ("target_event__isnull", False),
                            ),
                            models.Q(
                                ("status", "open"),
                                (
                                    "decision_type__in",
                                    frozenset(["collision", "conflict", "review_required"]),
                                ),
                            ),
                            models.Q(
                                ("status", "rejected"),
                                ("decision_type__in", frozenset(["ignored", "no_match"])),
                                ("target_event__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="earnings_reconciliation_decision_outcome_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actor_user__isnull", False),
                                models.Q(("reason", ""), _negated=True),
                                models.Q(("request_id", ""), _negated=True),
                            ),
                            models.Q(
                                ("actor_user__isnull", True),
                                ("sync_run__isnull", False),
                                ("request_id", ""),
                            ),
                            _connector="OR",
                        ),
                        name="earnings_reconciliation_decision_context_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("decision_key__regex", "^[0-9a-f]{64}$")),
                        name="earnings_reconciliation_decision_key_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rule_version__regex", "[^[:space:]]")),
                        name="earnings_reconciliation_decision_rule_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("supersedes__isnull", True),
                            models.Q(("supersedes", models.F("id")), _negated=True),
                            _connector="OR",
                        ),
                        name="earnings_reconciliation_decision_not_self",
                    ),
                    models.UniqueConstraint(
                        fields=("decision_key",), name="earnings_reconciliation_decision_key_unique"
                    ),
                ],
            },
        ),
    ]
