# Generated by Django 5.2.16 on 2026-09-24 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('earnings', '0005_earningsreconciliationdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPoolSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('selector_version', models.CharField(max_length=100)),
                ('enabled_index_codes', models.JSONField(default=list)),
                ('input_revision', models.CharField(editable=False, max_length=64)),
                ('pool_hash', models.CharField(editable=False, max_length=64)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-as_of_date', 'selector_version', 'pool_hash'),
                'indexes': [models.Index(fields=['as_of_date', 'selector_version'], name='earnings_mo_as_of_d_87f9d4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('selector_version__regex', '[^[:space:]]')), name='earnings_pool_snapshot_selector_version_not_empty'), models.CheckConstraint(condition=models.Q(('enabled_index_codes', []), _negated=True), name='earnings_pool_snapshot_enabled_indexes_not_empty'), models.CheckConstraint(condition=models.Q(('input_revision__regex', '^[0-9a-f]{64}$')), name='earnings_pool_snapshot_input_revision_valid'), models.CheckConstraint(condition=models.Q(('pool_hash__regex', '^[0-9a-f]{64}$')), name='earnings_pool_snapshot_hash_valid'), models.UniqueConstraint(fields=('as_of_date', 'selector_version', 'pool_hash'), name='earnings_pool_snapshot_identity_unique'), models.UniqueConstraint(fields=('as_of_date', 'selector_version', 'input_revision'), name='earnings_pool_snapshot_revision_unique')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringPoolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('basis', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_pool_members', to='companies.company')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='earnings.monitoringpoolsnapshot')),
            ],
            options={
                'ordering': ('snapshot', 'ordinal'),
                'constraints': [models.CheckConstraint(condition=models.Q(('basis', []), _negated=True), name='earnings_pool_member_basis_not_empty'), models.UniqueConstraint(fields=('snapshot', 'company'), name='earnings_pool_member_company_unique'), models.UniqueConstraint(fields=('snapshot', 'ordinal'), name='earnings_pool_member_ordinal_unique')],
            },
        ),
    ]
