# Generated by Django 5.2.16 on 2026-09-24 17:37
#
# Adds the explicit UNKNOWN domain value and changes the new EarningsEvent default.
# Existing rows are intentionally not rewritten because old default-derived values
# cannot be reliably distinguished from source-supported month_based facts.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_syncrun_provider_version_provenance'),
        ('companies', '0001_initial'),
        ('earnings', '0006_monitoringpoolsnapshot_monitoringpoolmember'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='earningscalendarobservation',
            name='earnings_calendar_observation_calendar_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='earningsevent',
            name='earnings_event_calendar_type_valid',
        ),
        migrations.AlterField(
            model_name='earningscalendarobservation',
            name='fiscal_calendar_type',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('month_based', 'Month-based'), ('week_based_52_53', '52/53-week'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='earningsevent',
            name='fiscal_calendar_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('month_based', 'Month-based'), ('week_based_52_53', '52/53-week'), ('other', 'Other')], default='unknown', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='earningscalendarobservation',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_calendar_type__isnull', True), ('fiscal_calendar_type__in', frozenset(['month_based', 'other', 'unknown', 'week_based_52_53'])), _connector='OR'), name='earnings_calendar_observation_calendar_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_calendar_type__in', frozenset(['month_based', 'other', 'unknown', 'week_based_52_53']))), name='earnings_event_calendar_type_valid'),
        ),
    ]
