# Generated by Django 5.2.16 on 2026-10-01 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_remove_auditrecord_audit_record_target_type_valid_and_more'),
        ('earnings', '0007_fiscal_calendar_unknown'),
        ('filings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingEarningsDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('RELEASE_FILING', 'Release filing'), ('PERIODIC_FILING', 'Periodic filing'), ('OTHER', 'Other')], max_length=32)),
                ('decision_type', models.CharField(choices=[('matched_release_filing', 'Matched release filing'), ('matched_periodic_filing', 'Matched periodic filing'), ('review_required', 'Review required'), ('no_match', 'No match'), ('manual_confirmed', 'Manually confirmed'), ('manual_rejected', 'Manually rejected')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=16)),
                ('classification', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('REVIEW_REQUIRED', 'Review required')], max_length=20, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('EXACT', 'Exact'), ('BOUNDED_WINDOW', 'Bounded window'), ('MANUAL', 'Manual')], max_length=20, null=True)),
                ('match_rule_version', models.CharField(max_length=100)),
                ('classification_rule_version', models.CharField(blank=True, default='', max_length=100)),
                ('decision_source', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=16)),
                ('match_factors', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=2000)),
                ('request_id', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_key', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_decisions', to=settings.AUTH_USER_MODEL)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_decisions', to='filings.filing')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_decisions', to='audit.sourceevidence')),
                ('source_raw_data_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_decisions', to='audit.rawdatarecord')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_decisions', to='earnings.filingearningsdecision')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_decisions', to='audit.syncrun')),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_decisions', to='earnings.earningsevent')),
            ],
            options={
                'ordering': ('-decided_at', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FilingEarningsLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('RELEASE_FILING', 'Release filing'), ('PERIODIC_FILING', 'Periodic filing'), ('OTHER', 'Other')], max_length=32)),
                ('release_filing_classification', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('REVIEW_REQUIRED', 'Review required')], max_length=20, null=True)),
                ('classification_reason', models.CharField(blank=True, default='', max_length=2000)),
                ('classification_rule_version', models.CharField(blank=True, default='', max_length=100)),
                ('match_rule_version', models.CharField(max_length=100)),
                ('confidence', models.CharField(choices=[('EXACT', 'Exact'), ('BOUNDED_WINDOW', 'Bounded window'), ('MANUAL', 'Manual')], max_length=20)),
                ('review_status', models.CharField(choices=[('auto', 'Automatic'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='auto', max_length=16)),
                ('review_reason', models.CharField(blank=True, default='', max_length=2000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_links', to='earnings.filingearningsdecision')),
                ('earnings_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_links', to='earnings.earningsevent')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_links', to='filings.filing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_links', to=settings.AUTH_USER_MODEL)),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_earnings_links', to='audit.sourceevidence')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='filingearningsdecision',
            index=models.Index(fields=['filing', 'relation_type', 'decided_at'], name='earnings_fi_filing__e41c64_idx'),
        ),
        migrations.AddIndex(
            model_name='filingearningsdecision',
            index=models.Index(fields=['target_event', 'decided_at'], name='earnings_fi_target__7639c7_idx'),
        ),
        migrations.AddIndex(
            model_name='filingearningsdecision',
            index=models.Index(fields=['status', 'decision_type', 'decided_at'], name='earnings_fi_status_f21fc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('relation_type__in', frozenset(['OTHER', 'PERIODIC_FILING', 'RELEASE_FILING']))), name='filing_earnings_decision_relation_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision_type__in', frozenset(['manual_confirmed', 'manual_rejected', 'matched_periodic_filing', 'matched_release_filing', 'no_match', 'review_required']))), name='filing_earnings_decision_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', frozenset(['open', 'rejected', 'resolved']))), name='filing_earnings_decision_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision_source__in', frozenset(['automatic', 'manual']))), name='filing_earnings_decision_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('classification__isnull', True), ('classification__in', frozenset(['NO', 'REVIEW_REQUIRED', 'YES'])), _connector='OR'), name='filing_earnings_decision_classification_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), ('confidence__in', frozenset(['BOUNDED_WINDOW', 'EXACT', 'MANUAL'])), _connector='OR'), name='filing_earnings_decision_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision_type__in', ('matched_release_filing', 'matched_periodic_filing', 'manual_confirmed')), ('status', 'resolved'), ('target_event__isnull', False)), models.Q(('decision_type', 'review_required'), ('status', 'open')), models.Q(('decision_type', 'no_match'), ('status', 'rejected'), ('target_event__isnull', True)), models.Q(('decision_type', 'manual_rejected'), ('status', 'rejected')), _connector='OR'), name='filing_earnings_decision_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision_type', 'matched_periodic_filing'), ('relation_type', 'PERIODIC_FILING'), ('classification__isnull', True), ('classification_rule_version', '')), models.Q(('decision_type', 'matched_release_filing'), ('relation_type', 'RELEASE_FILING'), ('classification__isnull', False), models.Q(('classification_rule_version', ''), _negated=True)), models.Q(('decision_type', 'manual_confirmed'), models.Q(models.Q(('relation_type', 'RELEASE_FILING'), ('classification', 'YES'), models.Q(('classification_rule_version', ''), _negated=True)), models.Q(('relation_type', 'PERIODIC_FILING'), ('classification__isnull', True), ('classification_rule_version', '')), _connector='OR')), models.Q(('decision_type__in', ('matched_release_filing', 'matched_periodic_filing', 'manual_confirmed')), _negated=True), _connector='OR'), name='filing_earnings_decision_classification_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('classification__isnull', True), models.Q(('classification_rule_version', ''), _negated=True), _connector='OR'), name='filing_earnings_decision_classification_version_required'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('match_rule_version__regex', '[^[:space:]]')), name='filing_earnings_decision_match_rule_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision_source', 'automatic'), ('sync_run__isnull', False), ('actor_user__isnull', True), ('request_id', '')), models.Q(('decision_source', 'manual'), ('actor_user__isnull', False), models.Q(('reason', ''), _negated=True), models.Q(('request_id', ''), _negated=True)), _connector='OR'), name='filing_earnings_decision_source_context_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision_key__regex', '^[0-9a-f]{64}$')), name='filing_earnings_decision_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('supersedes', models.F('id')), _negated=True), _connector='OR'), name='filing_earnings_decision_not_self'),
        ),
        migrations.AddConstraint(
            model_name='filingearningsdecision',
            constraint=models.UniqueConstraint(fields=('decision_key',), name='filing_earnings_decision_key_unique'),
        ),
        migrations.AddIndex(
            model_name='filingearningslink',
            index=models.Index(fields=['earnings_event', 'relation_type', 'review_status'], name='earnings_fi_earning_6cc4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='filingearningslink',
            index=models.Index(fields=['filing', 'relation_type'], name='earnings_fi_filing__f853ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(('relation_type__in', frozenset(['OTHER', 'PERIODIC_FILING', 'RELEASE_FILING']))), name='filing_earnings_link_relation_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', frozenset(['BOUNDED_WINDOW', 'EXACT', 'MANUAL']))), name='filing_earnings_link_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', frozenset(['auto', 'confirmed', 'rejected']))), name='filing_earnings_link_review_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(('release_filing_classification__isnull', True), ('release_filing_classification__in', frozenset(['NO', 'REVIEW_REQUIRED', 'YES'])), _connector='OR'), name='filing_earnings_link_classification_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('relation_type', 'RELEASE_FILING'), ('release_filing_classification__isnull', False)), models.Q(models.Q(('relation_type', 'RELEASE_FILING'), _negated=True), ('release_filing_classification__isnull', True)), _connector='OR'), name='filing_earnings_link_release_classification_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('relation_type', 'RELEASE_FILING'), models.Q(('classification_reason', ''), _negated=True), models.Q(('classification_rule_version', ''), _negated=True)), models.Q(models.Q(('relation_type', 'RELEASE_FILING'), _negated=True), ('classification_reason', ''), ('classification_rule_version', '')), _connector='OR'), name='filing_earnings_link_classification_provenance_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(('match_rule_version__regex', '[^[:space:]]')), name='filing_earnings_link_match_rule_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('review_status', 'auto'), ('reviewed_by__isnull', True), ('reviewed_at__isnull', True), ('review_reason', '')), models.Q(('review_status__in', ('confirmed', 'rejected')), ('reviewed_by__isnull', False), ('reviewed_at__isnull', False), models.Q(('review_reason', ''), _negated=True)), _connector='OR'), name='filing_earnings_link_review_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('review_status', 'confirmed'), _negated=True), models.Q(('relation_type', 'RELEASE_FILING'), _negated=True), ('release_filing_classification', 'YES'), _connector='OR'), name='filing_earnings_link_confirmed_release_yes'),
        ),
        migrations.AddConstraint(
            model_name='filingearningslink',
            constraint=models.UniqueConstraint(fields=('filing', 'earnings_event', 'relation_type'), name='filing_earnings_link_identity_unique'),
        ),
    ]
