# Generated by Django 5.2.16 on 2026-10-01 15:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_remove_auditrecord_audit_record_target_type_valid_and_more'),
        ('companies', '0001_initial'),
        ('earnings', '0008_filingearningsdecision_filingearningslink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorRelationsObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=64)),
                ('provider_version', models.CharField(max_length=100)),
                ('parser_version', models.CharField(max_length=100)),
                ('source_event_identity', models.CharField(max_length=255)),
                ('raw_position', models.PositiveIntegerField()),
                ('period_end_date', models.DateField()),
                ('period_type', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('FY', 'FY'), ('H1', 'H1'), ('H2', 'H2'), ('OTHER', 'Other')], max_length=8)),
                ('item_type', models.CharField(choices=[('release_confirmation', 'Release confirmation'), ('results_release', 'Results release'), ('call_notice', 'Conference call notice'), ('cancellation', 'Cancellation')], max_length=32)),
                ('estimated_release_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_release_date', models.DateField(blank=True, null=True)),
                ('estimated_release_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16)),
                ('confirmed_release_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_release_date', models.DateField(blank=True, null=True)),
                ('confirmed_release_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16)),
                ('earnings_release_at', models.DateTimeField(blank=True, null=True)),
                ('earnings_release_date', models.DateField(blank=True, null=True)),
                ('earnings_release_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16)),
                ('conference_call_at', models.DateTimeField(blank=True, null=True)),
                ('conference_call_date', models.DateField(blank=True, null=True)),
                ('conference_call_precision', models.CharField(choices=[('unknown', 'Unknown'), ('date_only', 'Date only'), ('exact_datetime', 'Exact datetime')], default='unknown', max_length=16)),
                ('release_session', models.CharField(blank=True, choices=[('pre_market', 'Pre-market'), ('after_market', 'After-market'), ('during_market', 'During market'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('cancellation', models.JSONField(blank=True, null=True)),
                ('source_observed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_observations', to='companies.company')),
                ('raw_data_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_observations', to='audit.rawdatarecord')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_observations', to='audit.datasource')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvestorRelationsDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('confirmed_schedule', 'Confirmed schedule'), ('updated_conference_call', 'Updated conference call'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('conflict', 'Conflict'), ('no_match', 'No match'), ('ignored', 'Ignored')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=16)),
                ('covered_fields', models.JSONField(blank=True, default=list)),
                ('rule_version', models.CharField(max_length=100)),
                ('match_factors', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=2000)),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_key', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_decisions', to=settings.AUTH_USER_MODEL)),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_decisions', to='audit.sourceevidence')),
                ('source_raw_data_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_decisions', to='audit.rawdatarecord')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_decisions', to='earnings.investorrelationsdecision')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_decisions', to='audit.syncrun')),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations_decisions', to='earnings.earningsevent')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='earnings.investorrelationsobservation')),
            ],
            options={
                'ordering': ('-decided_at', '-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='investorrelationsobservation',
            index=models.Index(fields=['source', 'source_event_identity'], name='earnings_in_source__589ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrelationsobservation',
            index=models.Index(fields=['company', 'period_end_date', 'period_type'], name='earnings_in_company_dba698_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.UniqueConstraint(fields=('raw_data_record', 'parser_version', 'source_event_identity'), name='investor_relations_observation_record_parser_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('provider_key__regex', '^[a-z][a-z0-9._-]{1,63}$')), name='investor_relations_observation_provider_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('provider_version__regex', '[^[:space:]]'), ('parser_version__regex', '[^[:space:]]'), ('source_event_identity__regex', '[^[:space:]]')), name='investor_relations_observation_identity_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_event_identity__startswith', 'internal:'), _negated=True), ('source_event_identity__regex', '^internal:ir:v1:[0-9a-f]{64}$'), _connector='OR'), name='investor_relations_observation_internal_namespace_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('period_type__in', frozenset(['FY', 'H1', 'H2', 'OTHER', 'Q1', 'Q2', 'Q3']))), name='investor_relations_observation_period_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', frozenset(['call_notice', 'cancellation', 'release_confirmation', 'results_release']))), name='investor_relations_observation_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('release_session__isnull', True), ('release_session__in', frozenset(['after_market', 'during_market', 'pre_market', 'unknown'])), _connector='OR'), name='investor_relations_observation_release_session_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('raw_position__gte', 1)), name='investor_relations_observation_raw_position_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='investor_relations_observation_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estimated_release_at__isnull', True), ('estimated_release_date__isnull', True), ('estimated_release_precision', 'unknown')), models.Q(('estimated_release_at__isnull', True), ('estimated_release_date__isnull', False), ('estimated_release_precision', 'date_only')), models.Q(('estimated_release_at__isnull', False), ('estimated_release_date__isnull', True), ('estimated_release_precision', 'exact_datetime')), _connector='OR'), name='investor_relations_observation_estimated_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_release_at__isnull', True), ('confirmed_release_date__isnull', True), ('confirmed_release_precision', 'unknown')), models.Q(('confirmed_release_at__isnull', True), ('confirmed_release_date__isnull', False), ('confirmed_release_precision', 'date_only')), models.Q(('confirmed_release_at__isnull', False), ('confirmed_release_date__isnull', True), ('confirmed_release_precision', 'exact_datetime')), _connector='OR'), name='investor_relations_observation_confirmed_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('earnings_release_at__isnull', True), ('earnings_release_date__isnull', True), ('earnings_release_precision', 'unknown')), models.Q(('earnings_release_at__isnull', True), ('earnings_release_date__isnull', False), ('earnings_release_precision', 'date_only')), models.Q(('earnings_release_at__isnull', False), ('earnings_release_date__isnull', True), ('earnings_release_precision', 'exact_datetime')), _connector='OR'), name='investor_relations_observation_earnings_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conference_call_at__isnull', True), ('conference_call_date__isnull', True), ('conference_call_precision', 'unknown')), models.Q(('conference_call_at__isnull', True), ('conference_call_date__isnull', False), ('conference_call_precision', 'date_only')), models.Q(('conference_call_at__isnull', False), ('conference_call_date__isnull', True), ('conference_call_precision', 'exact_datetime')), _connector='OR'), name='investor_relations_observation_conference_precision_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'release_confirmation'), _negated=True), models.Q(models.Q(('confirmed_release_precision', 'unknown'), _negated=True), ('estimated_release_precision', 'unknown')), models.Q(('confirmed_release_precision', 'unknown'), models.Q(('estimated_release_precision', 'unknown'), _negated=True)), _connector='OR'), name='investor_relations_observation_confirmation_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'results_release'), _negated=True), models.Q(models.Q(('earnings_release_precision', 'unknown'), _negated=True), ('estimated_release_precision', 'unknown'), ('confirmed_release_precision', 'unknown')), _connector='OR'), name='investor_relations_observation_results_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'call_notice'), _negated=True), models.Q(models.Q(('conference_call_precision', 'unknown'), _negated=True), ('earnings_release_precision', 'unknown'), models.Q(('confirmed_release_precision', 'unknown'), ('estimated_release_precision', 'unknown'), _connector='OR')), _connector='OR'), name='investor_relations_observation_call_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'cancellation'), _negated=True), models.Q(('cancellation__isnull', False), ('estimated_release_precision', 'unknown'), ('confirmed_release_precision', 'unknown'), ('earnings_release_precision', 'unknown'), ('conference_call_precision', 'unknown')), _connector='OR'), name='investor_relations_observation_cancellation_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('item_type', 'cancellation'), _negated=True), ('cancellation__isnull', True)), ('item_type', 'cancellation'), _connector='OR'), name='investor_relations_observation_cancellation_scope_valid'),
        ),
        migrations.AddIndex(
            model_name='investorrelationsdecision',
            index=models.Index(fields=['observation', 'decided_at'], name='earnings_in_observa_e0bb43_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrelationsdecision',
            index=models.Index(fields=['target_event', 'decided_at'], name='earnings_in_target__dca6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='investorrelationsdecision',
            index=models.Index(fields=['status', 'decision_type', 'decided_at'], name='earnings_in_status_9a5b67_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision_type__in', frozenset(['cancelled', 'confirmed_schedule', 'conflict', 'ignored', 'no_match', 'released', 'updated_conference_call']))), name='investor_relations_decision_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', frozenset(['open', 'rejected', 'resolved']))), name='investor_relations_decision_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), ('decision_type__in', frozenset(['cancelled', 'confirmed_schedule', 'released', 'updated_conference_call'])), ('target_event__isnull', False)), models.Q(('status', 'open'), ('decision_type', 'conflict')), models.Q(('status', 'rejected'), ('decision_type', 'no_match'), ('target_event__isnull', True)), models.Q(('status', 'rejected'), ('decision_type', 'ignored')), _connector='OR'), name='investor_relations_decision_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_user__isnull', False), models.Q(('reason', ''), _negated=True), models.Q(('request_id', ''), _negated=True)), models.Q(('actor_user__isnull', True), ('sync_run__isnull', False), ('request_id', ''), ('source_raw_data_record__isnull', False)), _connector='OR'), name='investor_relations_decision_context_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision_key__regex', '^[0-9a-f]{64}$')), name='investor_relations_decision_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('rule_version__regex', '[^[:space:]]')), name='investor_relations_decision_rule_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('supersedes', models.F('id')), _negated=True), _connector='OR'), name='investor_relations_decision_not_self'),
        ),
        migrations.AddConstraint(
            model_name='investorrelationsdecision',
            constraint=models.UniqueConstraint(fields=('decision_key',), name='investor_relations_decision_key_unique'),
        ),
    ]
